# Generated by Django 2.2.5 on 2021-07-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210702_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('other', 'Other'), ('male', 'Male')], max_length=10),
        ),
    ]
