# Generated by Django 2.2.5 on 2021-07-31 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_user_login_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_confirmed',
            new_name='email_verified',
        ),
    ]
