# Generated by Django 2.2.5 on 2021-08-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20210814_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('korean', 'Korean')], max_length=10),
        ),
    ]
